name: "Build PR"
on:
  pull_request:
    branches: [ main*, feat/*, hotfix/* ]

jobs:
  build:
    if: github.event_name != 'push'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
          TESTCONTAINERS_RYUK_DISABLED: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn -B -U verify
      # Write PR number to file
      - name: Write PR number to file
        run: echo "${{ github.event.pull_request.number }}" > pr-number.txt
      # Upload PR number artifact
      - name: Upload PR number artifact
        uses: actions/upload-artifact@v5
        with:
          name: pr-number
          path: pr-number.txt
      # Upload compiled classes
      - name: Upload Compiled Classes
        uses: actions/upload-artifact@v5
        with:
          name: compiled-classes
          path: target/classes
      # Upload Jacoco XML report(s)
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v5
        with:
          name: coverage-reports
          path: target/site/jacoco/jacoco.xml
